import json
import os
import urllib.request

PROJECT_ID = os.environ["SUPABASE_PROJECT_ID"]
TOKEN = os.environ["SUPABASE_ACCESS_TOKEN"]

SQL = """
create table if not exists public.hype_dashboard_trades (
  id bigint generated by default as identity primary key,
  venue text not null check (venue in ('perps', 'spot')),
  coin text not null,
  trade_id text not null,
  side text not null check (side in ('A', 'B')),
  price numeric not null,
  size numeric not null,
  value_usd numeric not null,
  trade_time timestamptz not null,
  raw jsonb not null default '{}'::jsonb,
  inserted_at timestamptz not null default now(),
  unique (venue, trade_id)
);

create index if not exists hype_dashboard_trades_venue_time_idx
  on public.hype_dashboard_trades (venue, trade_time desc);

create index if not exists hype_dashboard_trades_time_idx
  on public.hype_dashboard_trades (trade_time desc);

alter table public.hype_dashboard_trades enable row level security;

create or replace function public.hype_dashboard_delete_old_trades()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  deleted_count integer;
begin
  delete from public.hype_dashboard_trades
  where trade_time < now() - interval '31 days';
  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$$;

grant execute on function public.hype_dashboard_delete_old_trades() to service_role;
"""

url = f"https://api.supabase.com/v1/projects/{PROJECT_ID}/database/query"
body = json.dumps({"query": SQL}).encode()
request = urllib.request.Request(
    url,
    data=body,
    headers={
        "Authorization": f"Bearer {TOKEN}",
        "Content-Type": "application/json",
        "User-Agent": "hypedashboard-schema/1.0",
    },
)
with urllib.request.urlopen(request, timeout=60) as response:
    print(response.status)
    print(response.read().decode()[:1000])
